#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <resistestor_icons.h>

int32_t resistestor_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm resistestor!");

    return 0;
}
